# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build and fit an FD-classification penalised tree
#' 
#' @description instantiates and fits a Functional Data Penalised Optimial Randomised Decision Tree
#' @note The s3 class p.fdorct provides an interface for this method 
#' @param y labels vector. Note they have to be integers starting from 0
#' @param X_coeffs p x n matrix with the coefficients fitted in the smoothing (see the examples of the library), where p is the number of coeffients for func. datum and n the sample size
#' @param X_argvals vector of lower and upper bounds of the domain
#' @param X_basis_df the degrees of freedom of the basis
#' @param X_basis_degree the degree of the (b-spline) basis
#' @param basis_type the basis type string, BSpline is the only one currently supported
#' @param depth the tree depth. Make 
#' @param alpha the hyperparameter for the penalty in the objective function. Higher alpha, higher weight for the penalty
#' @þaram similarity method: the method to compute similarity between two functions (by default, L2 norm)
#' @param n_feats how features to use at each node of the tree to perform a split. An equal-length partition of the size of n_feats is created; each feat is the integral of the func. datum in a set that is part of the pariition
#' @param n_solve how many different trees to fit starting from different init points
#' @param gamma the randomisation factor for the ORCT, best kept default
#' @param seed random seed for reproducibility
pFdorct_Rcpp <- function(y, X_coeffs, X_argvals, X_basis_df, X_basis_degree, basis_type = "BSpline", depth = 2L, alpha = .1, similarity_method = "d0.L2", n_feats = 10L, n_solve = 20L, gamma = 512., seed = 41703192L) {
    .Call(`_FdPot_pFdorct_Rcpp`, y, X_coeffs, X_argvals, X_basis_df, X_basis_degree, basis_type, depth, alpha, similarity_method, n_feats, n_solve, gamma, seed)
}

predict_FdPot_Rcpp <- function(fitted_tree, X_coefs, result_idx) {
    .Call(`_FdPot_predict_FdPot_Rcpp`, fitted_tree, X_coefs, result_idx)
}

compute_func_datum_integral <- function(coefs, X_argvals, basis_df, basis_degree, n_times) {
    .Call(`_FdPot_compute_func_datum_integral`, coefs, X_argvals, basis_df, basis_degree, n_times)
}

get_bspline_internal_knots <- function(coefs, X_argvals, basis_df, basis_degree, n_feats) {
    .Call(`_FdPot_get_bspline_internal_knots`, coefs, X_argvals, basis_df, basis_degree, n_feats)
}

test_case_compute_dissim_and_feats <- function(X_coeffs, X_argvals, X_basis_df, X_basis_degree, n_feats = 4L) {
    invisible(.Call(`_FdPot_test_case_compute_dissim_and_feats`, X_coeffs, X_argvals, X_basis_df, X_basis_degree, n_feats))
}

